#!/usr/bin/env bash
# Dependencies: amixer

volume=$(amixer sget Master | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p")
state=$(amixer sget Master | grep -Eoe '\[(on|off)\]')

if   [[ $state == '[off]' ]]; then
	output="muted"
else
	output="$volume %"
fi

echo "$output"
